### PR TITLE
Fix 2022 update

### PR DESCRIPTION
**Pull request by alexcg1**
### PR type

- 🏆 **Enhancements**

### Purpose
- This fixes handling of…

Newer Jina versions, running on bare metal with no prep

### Why? 
- Things have moved on since this was created, and I think hosting a kick-ass protein search on examples.jina.ai would rock

### Feedback required over
- A quick pair of :eyes: on the code

### Legal
- [X] I have read and agreed to [the terms of contributing.](https://github.com/georgeamccarthy/protein_search/blob/license/.github/contributing.md)

### CODE REVIEW

**Comment by alexcg1** [comment]
Confirmed working on my machine (after changing endpoint to `0.0.0.0` - I thought best try on bare metal before `docker-compose`)

**Comment by alexcg1** [comment]
> Confirmed working on my machine (after changing endpoint to `0.0.0.0` - I thought best try on bare metal before `docker-compose`)

I tested indexing and querying from Streamlit frontend

**Comment by fissoreg** [comment]
Thank you @alexcg1 for getting back to this! All changes look good to me.

It would be nice to switch to the new DocArray package at a certain point, but for the moment I can merge and close.

**Comment by georgeamccarthy** [comment]
Great stuff!

**Pull request merged**
