### PR TITLE
feat: Show RCSB metadata on frontend.

### PR DESCRIPTION
**Pull request by fissoreg**
### PR type
🏆 **Enhancements**
- Getting some metadata from rcsb.org to show on the frontend.

### Purpose
- To actually understand if the results are meaningful (i.e. to evaluate the model) we need more details then the PDB ID.

### Why? 
- Make the prototype more usable and user-friendly.

### Feedback required over
- A quick pair of :eyes: on the code
- Discussion on what to add. For now we can merge this and deploy, but we will probably want to add/remove information. We can open an issue to discuss this.

### Mentions
- @georgeamccarthy

### CODE REVIEW

**Comment by georgeamccarthy** [comment]
Spinning proteins is an epic feature.
I'm gonna edit the title to make the purpose a little more specific.

**Comment by georgeamccarthy** [comment]
Really cool stuff! I'll test it out and see what it looks like.

**Comment by georgeamccarthy** [comment]
I'm getting errors trying to use gql

```
➜ pip install gql
WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /opt/homebrew/lib/python3.9/site-packages
sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
WARNING: Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /opt/homebrew/lib/python3.9/site-packages
sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /opt/homebrew/include/python3.9/UNKNOWN
sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9/UNKNOWN
WARNING: Value for scheme.scripts does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /opt/homebrew/bin
sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin
WARNING: Value for scheme.data does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /opt/homebrew
sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Requirement already satisfied: gql in /opt/homebrew/lib/python3.9/site-packages (2.0.0)
Requirement already satisfied: graphql-core<3,>=2.3.2 in /opt/homebrew/lib/python3.9/site-packages (from gql) (2.3.2)
Requirement already satisfied: promise<3,>=2.3 in /opt/homebrew/lib/python3.9/site-packages (from gql) (2.3)
Requirement already satisfied: six>=1.10.0 in /opt/homebrew/lib/python3.9/site-packages (from gql) (1.16.0)
Requirement already satisfied: requests<3,>=2.12 in /opt/homebrew/lib/python3.9/site-packages (from gql) (2.26.0)
Requirement already satisfied: rx<2,>=1.6 in /opt/homebrew/lib/python3.9/site-packages (from graphql-core<3,>=2.3.2->gql) (1.6.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.9/site-packages (from requests<3,>=2.12->gql) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.9/site-packages (from requests<3,>=2.12->gql) (2021.5.30)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.9/site-packages (from requests<3,>=2.12->gql) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from requests<3,>=2.12->gql) (2.0.3)

➜ pip uninstall gql
Found existing installation: gql 2.0.0
Uninstalling gql-2.0.0:
  Would remove:
    /opt/homebrew/lib/python3.9/site-packages/gql-2.0.0.dist-info/*
    /opt/homebrew/lib/python3.9/site-packages/gql/*
Proceed (Y/n)? Y
  Successfully uninstalled gql-2.0.0

➜ pip install --pre gql[all]
zsh: no matches found: gql[all]

➜ pip install --pre gql
WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /opt/homebrew/lib/python3.9/site-packages
sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
WARNING: Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /opt/homebrew/lib/python3.9/site-packages
sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /opt/homebrew/include/python3.9/UNKNOWN
sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9/UNKNOWN
WARNING: Value for scheme.scripts does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /opt/homebrew/bin
sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin
WARNING: Value for scheme.data does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /opt/homebrew
sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Collecting gql
  Downloading gql-3.0.0a6.tar.gz (86 kB)
     |████████████████████████████████| 86 kB 1.3 MB/s
Collecting graphql-core<3.2,>=3.1.5
  Downloading graphql_core-3.1.5-py3-none-any.whl (188 kB)
     |████████████████████████████████| 188 kB 1.6 MB/s
Collecting yarl<2.0,>=1.6
  Downloading yarl-1.6.3.tar.gz (176 kB)
     |████████████████████████████████| 176 kB 3.4 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting multidict>=4.0
  Downloading multidict-5.1.0.tar.gz (53 kB)
     |████████████████████████████████| 53 kB 1.9 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: idna>=2.0 in /opt/homebrew/lib/python3.9/site-packages (from yarl<2.0,>=1.6->gql) (3.2)
Building wheels for collected packages: gql, yarl, multidict
  Building wheel for gql (setup.py) ... done
  Created wheel for gql: filename=gql-3.0.0a6-py2.py3-none-any.whl size=34862 sha256=4a777de53ec0eddcbb36e6dbb66dc099437de3e6eb92d5cf98ebd915a7ec5363
  Stored in directory: /Users/georgeamccarthy/Library/Caches/pip/wheels/a7/29/1a/9709f3b2c98a2d811d8be839cba15af7e578815f0e8f87d96e
  Building wheel for yarl (PEP 517) ... done
  Created wheel for yarl: filename=yarl-1.6.3-cp39-cp39-macosx_11_0_arm64.whl size=121303 sha256=40d5164419a32cae8dd1b5c5da4149a463fadd6ab1b9fae585088cf272836285
  Stored in directory: /Users/georgeamccarthy/Library/Caches/pip/wheels/c2/03/d3/a7ea30efd0c84c03fd1caf7757949a1dedf797361267741ef0
  Building wheel for multidict (PEP 517) ... done
  Created wheel for multidict: filename=multidict-5.1.0-cp39-cp39-macosx_11_0_arm64.whl size=49478 sha256=ef34625338e4f47ac7ba120ca105c7a9d089edfff53a85f820c00098a0f54789
  Stored in directory: /Users/georgeamccarthy/Library/Caches/pip/wheels/30/e1/1c/e049eab71b71df690ef505f2c3d5ef4d0c583346bd22f5a85f
Successfully built gql yarl multidict
Installing collected packages: multidict, yarl, graphql-core, gql
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /opt/homebrew/include/python3.9/multidict
  sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9/multidict
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /opt/homebrew/include/python3.9/yarl
  sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9/yarl
  Attempting uninstall: graphql-core
    Found existing installation: graphql-core 2.3.2
    Uninstalling graphql-core-2.3.2:
      Successfully uninstalled graphql-core-2.3.2
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /opt/homebrew/include/python3.9/graphql-core
  sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9/graphql-core
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /opt/homebrew/include/python3.9/gql
  sysconfig: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9/gql
Successfully installed gql-3.0.0a6 graphql-core-3.1.5 multidict-5.1.0 yarl-1.6.3

➜ streamlit run frontend/app.py
2021-07-29 17:13:43.685 Traceback (most recent call last):
  File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.8/site-packages/streamlit/script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
  File "/Users/georgeamccarthy/Documents/workspace/python/protein_search/frontend/app.py", line 4, in <module>
    from gql import gql, Client
ModuleNotFoundError: No module named 'gql'
```

**Comment by fissoreg** [comment]
My bad, I didn't update the requirements. Can you try the following line?

`pip install --pre "gql[aiohttp]"`

I'll try to update the `requirements.txt` in the meanwhile.

**Comment by georgeamccarthy** [comment]
No worries, I tried that but I was facing issues because my pip version was for python 3.9 and my python was 3.8! I've corrected that and the install has worked!

**Comment by georgeamccarthy** [comment]
The metadata is great! Good job. I'm noticing that the proteins aren't loading for me. Are they for you?

Screenshot 2021-07-29 at 17 27 09

**Comment by georgeamccarthy** [comment]
Also getting a big dump on the frontend

Screenshot 2021-07-29 at 17 28 17

**Comment by georgeamccarthy** [comment]
I just had to disable my add blocker! Looks great, loving the spinning and gonna merge :)

Screenshot 2021-07-29 at 17 30 16

**Comment by fissoreg** [comment]
The dump on the frontend is a problem indeed. I ignored it for now, I think it is some logging from `gql`. We can probably disable it using the right arguments.

**Pull request merged**
