### PR TITLE
Add license, contributing terms and update PR to include checkbox.

### PR DESCRIPTION
**Pull request by georgeamccarthy**
### PR type
- 🏠 **Internal** 

### Purpose
- Add license, contributing terms and update PR to include checkbox.

### Why? 
- Required before accepting contributions from others.

### Feedback required over
- Read through the documents.

### Mentions
- @fissoreg 

### References
- https://github.com/mperham/sidekiq
- https://www.gov.uk/government/publications/copyright-notice-assignment-of-copyright
- https://choosealicense.com/licenses/

**Not legal advice**

### CODE REVIEW

**Comment by georgeamccarthy** [comment]
@fissoreg Go ahead and merge if you agree with the changes. :)

**Comment by fissoreg** [comment]
Good to me! Merging this.

**Comment by Rubix982** [comment]
@georgeamccarthy why is the `contributing.md` not at the root and instead in `.github`?

**Comment by georgeamccarthy** [comment]
Good shout, I've moved it :) https://github.com/georgeamccarthy/protein_search/commit/3d193d6202298b33f3530602c5f01a170d4f36a5

**Pull request merged**
